version: '3.8'
services:
  application:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: gopkg
    dns: 1.1.1.1
    logging:
      driver: syslog
      options:
        syslog-address: "udp://host.docker.internal:5514"
        tag: gopkg
    depends_on:
      - syslog-ng
  
  syslog-ng:
    build:
      context: ./syslog
      dockerfile: Dockerfile
    container_name: syslog-ng
    dns: 1.1.1.1
    ports:
    - "5514:514/udp"
